name: ci

on:
  push:
    branches:
      - main

jobs:
  pnpm-5:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [16.0.0-alpine3.13]
        pnpm: [5.14.3]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./pnpm/Dockerfile
          build-args: |
            node=${{ matrix.node }}
            pnpm=${{ matrix.pnpm }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.node }}-${{ matrix.pnpm }}
  pnpm-6:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [16.13.1-alpine3.15]
        pnpm: [6.24.4]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./pnpm/Dockerfile
          build-args: |
            node=${{ matrix.node }}
            pnpm=${{ matrix.pnpm }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pnpm:${{ matrix.node }}-${{ matrix.pnpm }}
